### ISSUE TITLE
create schema with union type 

### ISSUE THREAD

**Issue by missbruni** [elierotenberg/fastify-zod#14]
I am having issues when trying to validate a schema with a schema union type. To simplify the description I have created a small example. My `test` endpoint here can receive two types of query params. So the querystring can either receive Name:

```
export const Name = z.object({
  name: z.string(),
  lastName: z.string()
});
```

or It can receive Address:
```
export const Address = z.object({
  street: z.string(),
  postcode: z.string()
});
```
So the schema type for my endpoint would be a union of Name and Address:
```
const UserDetails = z.union([Name, Address]);
const { schemas, $ref } = buildJsonSchemas({ UserDetails });
const test: FastifyPluginAsync = async (fastify) => {
  for (const schema of schemas) {
    fastify.addSchema(schema);
  }

  fastify.route({
    method: 'GET',
    url: '/',
    schema: {
      operationId: `userDetails`,
      querystring: $ref(`UserDetails`)
    },
    handler: async function authTokenHandler(request: FastifyRequest, reply: FastifyReply) {
      return 'Schema Validated, All Good!';
    }
  });
};
export default test;
```

The issue I am having is that the validation is not recognizing which type to enforce when a param is missing. So if test calling:
```
/test?name=someName // "querystring should have required property 'lastName', querystring should have required property 'street', querystring should match some schema in anyOf"
```
And here I expected the validation to have identified the type as Name, and only required lastName. But no, it is requiring street as well. Although is a different type from the one I am sending. 

Is this expected ? I would have expected Name Schema to have been identified by sending `name` and only enforced that type on the schema instead of both types from the union. Is there a way around this?

**Comment by elierotenberg** [comment]
Hello,

Hello,

I'm sorry, as mentioned in https://github.com/elierotenberg/fastify-zod/issues/15 for some reason GitHub notifications got lost in my mailbox.

There were 2 issues with the example you provide.

The first is lack of support for `querystring`, which is now available in [1.0.0](https://github.com/elierotenberg/fastify-zod/commit/4602f15029f4c77344d69f3463da2869314d2b14).

The second is, I think, due to how discriminated unions work. Without a discriminator property (in [OpenAPI](https://swagger.io/specification/#discriminator-object) as well as in [TypeScript](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-func.html#discriminated-unions)), it is not possible to know for sure which branch of the union you are referring to. With a discriminator property however, the correct error is raised. I [added a test to illustrate](https://github.com/elierotenberg/fastify-zod/blob/4602f15029f4c77344d69f3463da2869314d2b14/src/__tests__/issues.test.ts#L81).

Does this answer cover your needs?
